# Generated by Django 3.1 on 2020-10-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0004_userprofile_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Farooq Mohammad Mulla', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('mem', 'MEMBER'), ('lead', 'TEAM LEADER'), ('t_lead', 'SAIAYNS LEADER')], default='mem', max_length=20),
        ),
    ]
