# Generated by Django 3.1 on 2020-10-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0005_auto_20201018_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
