# Generated by Django 3.1 on 2020-10-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0006_auto_20201018_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('MEMBER', 'MEMBER'), ('TEAM LEADER', 'TEAM LEADER'), ('SAIAYNS LEADER', 'SAIAYNS LEADER')], default='mem', max_length=20),
        ),
    ]
