# Generated by Django 3.1 on 2020-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0008_auto_20201018_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pro_pic',
            field=models.ImageField(default='pro_pics/default.png', upload_to='pro_pics/'),
        ),
    ]
