# Generated by Django 3.1 on 2020-09-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('Functionality', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('ttl_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
