# Generated by Django 3.1 on 2020-09-20 06:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_subscriber_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='null', max_length=128, region=None),
        ),
    ]
