# Generated by Django 3.1 on 2020-09-21 08:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200921_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='please enter along with your country code. e.g "+91"', max_length=128, region=None),
        ),
    ]
