# Generated by Django 3.1 on 2020-09-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Functionality',
            field=models.TextField(blank=True, default='Not Mentioned', null=True),
        ),
    ]
