# Generated by Django 3.1 on 2020-09-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200923_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='author',
        ),
    ]
