# Generated by Django 3.1 on 2020-10-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200927_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='phone',
        ),
    ]
