# Generated by Django 3.1 on 2020-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201014_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(default='username', help_text='This will be your username', max_length=55),
        ),
    ]
