# Generated by Django 3.1 on 2020-10-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201018_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(null=True),
        ),
    ]
