# Generated by Django 3.1 on 2020-10-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20201019_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_slug',
            new_name='slug',
        ),
    ]
